# Generated by Django 5.1.6 on 2025-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
