# Generated by Django 5.1.6 on 2025-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healedelements',
            name='new_css_selector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healedelements',
            name='new_xpath_absolute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healedelements',
            name='past_css_selector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healedelements',
            name='past_xpath_absolute',
            field=models.TextField(blank=True, null=True),
        ),
    ]
