# Generated by Django 5.1.6 on 2025-04-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_healedelements_new_css_selector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionsequence',
            old_name='name',
            new_name='number',
        ),
    ]
