# Generated by Django 5.1.6 on 2025-04-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_executionsequence_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionsequence',
            old_name='number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='scenarios',
            name='execution_sequence',
        ),
        migrations.RemoveField(
            model_name='scenarios',
            name='order',
        ),
        migrations.CreateModel(
            name='SequenceScenario',
            fields=[
                ('sequence_scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('execution_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_scenarios', to='accounts.executionsequence')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_scenarios', to='accounts.scenarios')),
            ],
            options={
                'db_table': 'sequence_scenario',
                'ordering': ['order'],
                'unique_together': {('execution_sequence', 'scenario')},
            },
        ),
    ]
