# Generated by Django 5.1.6 on 2025-04-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_name_executionsequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='scenarios_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
