# Generated by Django 5.1.6 on 2025-05-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_scenarios_scenarios_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTuningData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_attributes', models.JSONField()),
                ('matched_attributes', models.JSONField()),
                ('label', models.BooleanField(help_text='True if healing was correct, False if incorrect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_tuning_data', to='accounts.execution')),
            ],
            options={
                'verbose_name_plural': 'Fine Tuning Data',
                'db_table': 'fine_tuning_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
